In [1]:
import numpy as np 
n=int(input('enter range of array'))
a1=np.arange(0,int(n))
for i in range(0,n):
    print('enter element at index',i)
    a1[i]=int(input())


enter range of array10
enter element at index 0
23
enter element at index 1
43
enter element at index 2
45
enter element at index 3
65
enter element at index 4
78
enter element at index 5
98
enter element at index 6
67
enter element at index 7
98
enter element at index 8
09
enter element at index 9
56


In [2]:
x=int(input('no. u want to search '))
a1

no. u want to search 45


array([23, 43, 45, 65, 78, 98, 67, 98,  9, 56])

In [3]:
c=0
for i in range(0,n):
    if(a1[i]==x):
        print('element is present at index ',i)
        c=1
        break
if(c==0):
    print('element not found')

element is present at index  2


In [4]:
s=np.where(a1==x)

In [5]:
print(s)

(array([2], dtype=int64),)


In [6]:
a2=np.sort(a1)
print(a1)

[23 43 45 65 78 98 67 98  9 56]


In [7]:
print(a2)

[ 9 23 43 45 56 65 67 78 98 98]


In [8]:
lar=a2[len(a2)-1]
print(lar)

98


In [9]:
sma=a2[0]
print(sma)

9


In [10]:
a3=a1[::-1]

In [11]:
print(a3)

[56  9 98 67 98 78 65 45 43 23]


In [12]:
print('enter rotation pt.')
k=int(input())

enter rotation pt.
3


In [13]:
a4=a1[0:k]

In [14]:
print(a4)

[23 43 45]


In [15]:
a5=a1[k:n]

In [16]:
print(a5)

[65 78 98 67 98  9 56]


In [17]:
a=np.concatenate((a5, a4))

In [18]:
print(a)

[65 78 98 67 98  9 56 23 43 45]


In [19]:
#rotating a func by kth posi

In [20]:
def rotate(arr,n,k):
    k=k%n
    for i in range(k):
        t=arr[n-1]
        for j in range(n-1,0,-1):
            arr[j]=arr[j-1]
        arr[0]=t
    return arr


In [23]:
print('enter rotation pt.')
kr=int(input())


enter rotation pt.
3


In [24]:
ar=a1[0:k]

In [25]:
ar=ar[::-1]

In [27]:
ar1=a1[k:n]

##### 

In [28]:
arr=np.concatenate((ar1, ar))

In [29]:
print(arr)

[65 78 98 67 98  9 56 45 43 23]


In [39]:
a1


array([45, 65, 78, 98, 56, 67, 98,  9, 23, 43])

In [40]:
ar
a8=a1

In [41]:
print(rotate(a8,len(a2),3))

[ 9 23 43 45 65 78 98 56 67 98]
