In [1]:
#numpy array

In [38]:
print('aditi'*100)

aditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditiaditi


In [7]:
import numpy as np

In [8]:
#creating an array
arr=np.array((1,2,3,4,5))

In [9]:
arr

array([1, 2, 3, 4, 5])

In [12]:
#datattype of an array
arr=np.array([1,2,3,4],dtype=float)

In [13]:
arr

array([1., 2., 3., 4.])

In [14]:
#initialising an array

In [27]:
arr=np.array([],dtype='S')
arr=arr.astype(int)

In [17]:
arr=np.arange(10,40,2)

In [18]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [22]:
arr=np.insert(arr,3,int(40))

In [23]:
arr

array([10, 12, 14, 40, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [25]:
arr=np.append(arr,59)
arr=np.delete(arr,14)

In [26]:
arr

array([10, 12, 14, 40, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 38, 59])

In [28]:
#numpy site for refrence

In [29]:
#2d array matrix

In [33]:
mat=np.array([[1,2,3,4],[5,6,7,8],[9,10,12,13]])

In [34]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 12, 13]])

In [35]:
print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 12 13]]


In [49]:
#speed 
a=[i for i in range(10000000)]
b=[i for i in range(10000000,20000000)]
c=[]
import time
start=time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)    

1.8504302501678467


In [50]:
a1=[i for i in range(10000000)]
b1=[i for i in range(10000000,20000000)]
import time
start=time.time()
c1=a1+b1
print(time.time()-start)    

0.10538911819458008


In [51]:
mat[1]

array([5, 6, 7, 8])

In [52]:
mat[1,3]

8

In [53]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 12, 13]])

In [54]:
#3d array

In [55]:
d3=np.array([[[1,2,3,4],[5,6,7,8]],[[9,8,10,11],[13,14,15,16]]])

In [56]:
d3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9,  8, 10, 11],
        [13, 14, 15, 16]]])

In [ ]:
dn=np.array([3],ndarray=5)